language: objective-c
osx_image: xcode7.2
before_install:
  - brew update > /dev/null; if brew outdated | grep -qx xctool; then brew upgrade xctool; fi  # Ensure that xctool is up-to-date
xcode_workspace: 'Example/VOKUtilities.xcworkspace'
matrix:
  include:
    - xcode_scheme: VOKUtilities-Example
      xcode_sdk: iphonesimulator
    - xcode_scheme: VOKUtilities-tvOS
      xcode_sdk: appletvsimulator
    - xcode_scheme: VOKUtilities-OSX
      xcode_sdk: macosx
after_script:
    - pod lib lint